const colors = {
  light: {
    text: "#0e0e0f",
    tint: "#7c5cfc",
    background: "#f5f5f7",
    foreground: "#0e0e0f",
    card: "#ffffff",
    cardForeground: "#0e0e0f",
    primary: "#7c5cfc",
    primaryForeground: "#ffffff",
    secondary: "#ebebed",
    secondaryForeground: "#0e0e0f",
    muted: "#ebebed",
    mutedForeground: "#8e8e93",
    accent: "#a78bfa",
    accentForeground: "#ffffff",
    destructive: "#ff3b30",
    destructiveForeground: "#ffffff",
    border: "#e0e0e5",
    input: "#e0e0e5",
  },
  dark: {
    text: "#f0f0f2",
    tint: "#9d7dfd",
    background: "#0e0e0f",
    foreground: "#f0f0f2",
    card: "#1a1a1d",
    cardForeground: "#f0f0f2",
    primary: "#9d7dfd",
    primaryForeground: "#0e0e0f",
    secondary: "#252528",
    secondaryForeground: "#f0f0f2",
    muted: "#252528",
    mutedForeground: "#8e8e93",
    accent: "#7c5cfc",
    accentForeground: "#ffffff",
    destructive: "#ff453a",
    destructiveForeground: "#ffffff",
    border: "#2c2c30",
    input: "#2c2c30",
  },
  radius: 12,
};

export default colors;
