const colors = {
  light: {
    background: "#0a0a0a",
    foreground: "#ffffff",
    card: "#141414",
    card2: "#1c1c1c",
    cardForeground: "#ffffff",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#1c1c1c",
    secondaryForeground: "#ffffff",
    muted: "#1c1c1c",
    mutedForeground: "#a1a1aa",
    accent: "#3b82f6",
    accentForeground: "#ffffff",
    accentGreen: "#22c55e",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#141414",
    text: "#ffffff",
    tint: "#3b82f6",
  },
  dark: {
    background: "#0a0a0a",
    foreground: "#ffffff",
    card: "#141414",
    card2: "#1c1c1c",
    cardForeground: "#ffffff",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#1c1c1c",
    secondaryForeground: "#ffffff",
    muted: "#1c1c1c",
    mutedForeground: "#a1a1aa",
    accent: "#3b82f6",
    accentForeground: "#ffffff",
    accentGreen: "#22c55e",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#141414",
    text: "#ffffff",
    tint: "#3b82f6",
  },
  radius: 12,
};

export default colors;
